# Unit Level Models
\label{sec:unit_level}

The Battese-Harter-Fuller (BHF) model, which can also be regarded as a linear
mixed model, was introduced by @Bat88. The main focus of the present Thesis is
the extension of area level models. However some recent advances in the field,
especially with respect to robust estimation methodology, have been made for
unit level models. In Chapter \ref{chap:rfh} these results are applied to the
area level; here the basic unit level model and unit level notation is reviewed
preparatory to more details in Section \ref{sec:saerobust} below. A review of
unit level models in the context of linear mixed models and EBLUP based
predictions can be found in @Jia06 and also in @Rao03 and in @Rao15 who also
review a variety of extensions.

The unit level model of @Bat88 can be expressed as linear mixed model by:
\empty{
\begin{align}
	 y_{ij} = \sij{\mat{x}}^\top\pmat\beta + \si{\re} + \sij{e} \label{eq:bhf}
\end{align}
}where $y_{ij}$ denotes the response of unit $j = 1, \dots, N_i$ in area $i = 1,
\dots, D$. The random effects, $\si{\re}$, are independent and identically 
distributed following a normal distribution such that $\re_i \sim \Distr{N}(0, 
\sigre)$. The error terms $\sij{e}$ are i.i.d. following a normal distribution 
with zero mean and variance $\sigma_e^2$. Furthermore the random effect and 
model error are independent. $\sij{\mat{x}}$ denote the auxiliary variables for
the $j$th unit in the $i$th area.

Following @Rao15[pp. 78 ff] this model can be split into sampled and non-sampled
units. Let the set of $n$ sampled and $N-n$ non-sampled units be denoted by $S$
and $R$ respectivey. The sets can furthermore be split into the distinct $S_1 
\cup \dots \cup S_D$ and $R_1 \cup \dots \cup R_D$, where $S_i$ and $R_i$ denote
the sampled and non sampled units in area $i = 1, \dots, D$, respectively. Then
\eq{eq:bhf} can be written in matrix notation as
\empty{
\begin{align*}
\mat{y} = 
  \begin{pmatrix}\mat{y}_S\\\mat{y}_R\end{pmatrix} =
  \begin{pmatrix}\mat{X}_S\\\mat{X}_R\end{pmatrix} \pmat\beta +
  \begin{pmatrix}\mat{Z}_S\\\mat{Z}_R\end{pmatrix} \pmat\re + 
  \begin{pmatrix}\mat{e}_S\\\mat{e}_R\end{pmatrix}
\end{align*}
}where the subscripts $R$ and $S$ denote respectively the sampled and 
non-sampled part of the model. The fundamental assumption of this representation
is that the sampled units follow the population model. This is plausible under 
simple random sampling within each domain and, as @Rao15[79] note, also when
$\mat{X}_S$ contains the variables used for sampling.

These results can now be used to derive an EBLUP for the target statistic. In 
principle this also happens according to Section \ref{sec:blup}; however we are 
generally not interested in a prediction at unit level but for the area level 
target statistic. Following @Rao15[pp. 174 ff] an EBLUP under model \eq{eq:bhf} 
for the ith area mean can be derived as
\empty{
\begin{align}
\label{eq:bhfeblup}
\hat{\theta}_i^{BHF} = N_i^{-1} \Paran{\sum_{j \in S_i} y_{ij} + 
  \sum_{j\in R_i}(\sij{\mat{x}}^\top\hat{{\pmat\beta}} + \si{\hat{\re}})}
\end{align}
}where $\hat{\pmat\beta}$ denotes the BLUE of $\pmat\beta$ which is estimated
using the sampled information. Note that this predictor is based on the
auxiliary information for each unit in the non-sampled part of the population.
It may be unrealistic to have such information for each observation. This
assumption can be relaxed by using the area means of the population to make
domain predictions; however this information needs to be available to the
analyst. The unknown parameters of the model, i.e. $\pmat\beta$, $\sigre$ and
$\sigma_e^2$, can be estimated using standard ML and REML estimation techniques
and are based on the sampled data.

A wide range of MSPE estimators have been proposed for basic unit level small 
area methods -- a comprehensive review of these methods can be found in
@Rao15[179 ff]. Among these methods is an unconditional MSPE estimator which has
been proposed by @Dat00. For the robust extension of \eq{eq:bhfeblup}, which is 
introduced in the following Section, a number of methods are discussed in more
depth in Section \ref{sec:robustmse}.
