# Bias Correction
\label{sec:rfhbiascorrection}

The discussion in Section \ref{sec:robustbc} already highlighted the importance
of addressing the potential bias of a robust prediction when we suspect
non\hyp{}symmetric outliers. @Cha14 and @Jio13 have suggested different
corrections to the unit level REBLUP to take this prediction bias into account.
However the methods reviewed are based on the estimation of the within domain
prediction error; this approach is not directly applicable to area level models
since we may only have a single *observation* per domain. 

However the general problem remains. To find a solution we need to review the 
different kinds of outliers observable at the area level. In Section 
\ref{sec:rfh_framework} we distiguished between two types: area level and unit 
level outliers. Following @Bel06 area level outliers are values with large 
absolute values in the random effect and thus are values for which the synthetic
regression estimator is a poor fit. Independetly of this question @Fay79 refer 
to @Efr71 and @Efr72 who argue that the Bayes Estimator and the Emperical Bayes 
Estimator may improve the overall prediction performance but may be ill suited 
for specific domains. In essence this also describes the situation in which area
level outliers are present in the data and we are driven to use a robust
estimation procedure since we shrink the prediction towards a global conditional
mean. Although this may improve the overall quality of the predictions it will
not improve the prediction for the outlying domains.

In this setting we can address area level outliers in the same way as was 
already discussed by @Fay79. Following their results the idea is to bound the 
area level predictions using the known sampling variances -- @Efr71 and @Efr72 
refer to this strategy as a *limited translation estimator*. Hence we can modify
the REBLUP of equation \eq{eq:area_reblup} into a bias corrected version:
\empty{
\begin{align}
\label{eq:area_reblup_bc}
\hat{\theta}^{REBLUP-BC}_i = 
  \begin{cases}
    y_i - c & \text{if } \hat{\theta}^{REBLUP}_i < y_i - c  \\
    \hat{\theta}^{REBLUP}_i & \text{if } y_i - c \leq \hat{\theta}^{REBLUP}_i \leq y_i + c \\
    y_i + c & \text{if } \hat{\theta}^{REBLUP}_i > y_i + c \\
  \end{cases}
\end{align}
}with $i = 1, \dots, n$ where $c$ is a constant. @Fay79 suggest to set $c =
\sigma_{ei}$ to balance the tradeoff between loss in efficiency and gain in
reduced bias. This approach can be directly applied to the spatial and temporal
extensions and thus similarly to the area level REBLUP the area level REBLUP-BC in
\eq{eq:area_reblup_bc} acts as a placeholder for all extensions.

Since we need the pseudolinear representation below, we can state
\eq{eq:area_reblup_bc} as:
\empty{
\begin{align*}
\hat{\theta}^{REBLUP-BC}_i = \hat{\mat{w}}^{*\top}_i \mat{y}
\end{align*}
}where $\hat{\mat{w}}^{*\top}_i$ denotes the vector of weights given the 
parameter estimates for $\pmat\beta$, $\pmat\delta$, and the prediction of
$\mat{u}$:
\empty{
\begin{align*}
\hat{\mat{w}}^{*}_i = 
  \begin{cases}
    (1 - c / y_i) \mat{1}(j = i) & \text{if } \hat{\theta}^{REBLUP}_i < y_i - c  \\
    \hat{\mat{w}}_i & \text{if } y_i - c \leq \hat{\theta}^{REBLUP}_i \leq y_i + c \\
    (1 + c / y_i) \mat{1}(j = i) & \text{if } \hat{\theta}^{REBLUP}_i > y_i + c \\
  \end{cases}
\end{align*}
}where $\mat{1}(j = i)$ denotes a vector where the element $j = i$ is equal to
one and zero otherwise.

This solution may be beneficial when we observe area level outliers. However it 
is unclear how this modification relates to the scenario in which we have 
asymmetric unit level outliers. In fact this is a situation which can hardly be 
targeted by an area level correction without additional information. In Chapter 
\ref{chap:results_model_based} this issue is addressed again in model based 
simulation studies.

