# Direct Estimators
\label{sec:theory_sae_direct}

In this Chapter a general overview of the SAE field is provided. Here I begin
with a simple direct estimator and notation which is then used throughout the
Thesis. The area models later introduced are all based on some direct estimator.
This direct estimator can be any statistic; however I implicitly often refer to
it as an estimator for the population mean. This may be  plausible when we keep
in mind that the context of this Thesis is to study outlier robust methods; and
in this context it may be most intuitive when we consider the population mean
and a simple estimator as a starting point. @Leh09 give a more comprehesive
overview of direct estimators and design based methods.

Let a population be denoted by $U$, consisting of $N$ units, which can be devided
into $D$ distinct domains or areas $U_1 \cup \dots \cup U_D$. Each area is of
size $N_i$, with $i = 1, \dots, D$ denoting area $i$, such that $N = \sum_{i =
  1}^D N_i$. $S$ denotes a sample from $U$ which in turn can be devided into $S_1
\cup \dots \cup S_D$, where $n$ is the sample size of $S$ and $n_i$ of $S_i$
  such that $n = \sum_{i = 1}^D n_i$.

Let $\mat{y}$ define the characteristic of interest and $y_{ij}$ the response value 
for unit $j$ with $j = 1, \dots, N_i$ in area $i$. Furthermore let the target 
quantity be the population mean in area $U_i$ defined by $\theta_i = \bar{Y}_i =
\frac{1}{N_i}\sum_{j = 1}^{N_i} y_{ij}$ . Note that the target quantity is not
necessarily a mean but can be any statistic in the population.

Given that the sample is drawn with simple random sampling without replacement
(SRSWOR), a design unbiased estimator is given by

\empty{
\begin{align}
\bar{y}_i = \frac{1}{n_i}\sum_{j = 1}^{n_i} y_{ij}\label{eq:sampleMean}
\end{align}
}with its design variance $\Exp{V}(\bar{y}_i|n_i) = (S_i^2 / n_i) \Paran{1 - n_i 
/ N_i}$ where $S_i^2 = 1 / (N_i - 1) \sum_{j = 1}^{N_i} \Paran{y_{ij} - 
\bar{Y}_i}^2$. To estimate the sampling variance, $S^2_i$ can be replaced by 
$s_i^2$ being an estimator using the sampled data, i.e. $s_i^2 = 1 / (n_i - 1) 
\sum_{j = 1}^{n_i} \Paran{y_{ij} - \bar{y}_i}^2$. Note that $n_i$ is random
under SRSWOR such that specific areas can have very few or even no sampled
units.
