# Extensions to the Fay-Herriot Model

In the following sections the models under study are reviewed. This includes the
methods reviewed in Section \ref{sec:theory_sae_fh_extensions} but also the FH 
model. These models will be framed in the context of linear mixed models since 
the robust estimation equations are - where possible - stated for the general 
case of linear mixed models. Especially for the optimisation of the model
specifc variance parameters it will be necessary to give some results for each
model. In these situations the following sections will act as a reference point
in order to maintain the flow of reading.

## Fay-Herriot Model

For a review of the FH model see Section \ref{sec:theory_sae_fh}. In the 
following the model is framed as a linear mixed model in order to achieve a 
consistent notation for the robust parameter estimation. The model can be stated
as:
\empty{
\begin{align*}
\mat{y} & = \mat{X} \pmat\beta + \mat{Z}\mat{u} + \mat{e} \\
\mat{u} & \sim \Distr{N}\Paran{\mat{0}_D, \mat{V}_u} \\
\mat{e} & \sim \Distr{N}\Paran{\mat{0}_D, \mat{V}_e}
\end{align*}
}where $\mat{y}$ denotes the $(D \times 1)$ vector of observed direct 
estimates; $\mat{X}$ the $(D \times P)$ design matrix; $\pmat\beta$ the $(P 
\times 1)$ vector of regression coefficients; $\mat{Z} = \mat{I}_{D}$ 
is an identity matrix; $\mat{u}$ is the $(D \times 1)$ vector of random effects; 
and $\mat{e}$ is the $(D \times 1)$ vector of sampling errors. Furthermore
$\mat{0}_D$ denotes a $(D \times 1)$ vector containing zeros; $\mat{V}_u = 
\mat{V}_u(\sigma_\re^2) = \sigma_\re^2 \mat{I}_{D \times D}$ is the variance 
covariance matrix of $\mat{u}$; and $\mat{V}_e = \Diag{\{\sige\}_{i = 1}^D}$ 
with known sampling variances $\sige$. Furthermore $\mat{u}$ and $\mat{e}$ are
independent. The unknown model parameters are $\pmat\beta$ and $\pmat\delta =
(\sigre)$.


## Spatial Fay-Herriot Model

For a review of the spatial extension to the FH model see section
\ref{sec:theory_sae_fh_spatial}. Here model \eq{eq:sfh} is represented as linear
mixed model and as such it can be represented as:
\empty{
\begin{align*}
\mat{y} & = \mat{X} \pmat\beta + \mat{Z}\mat{u} + \mat{e} \\
\mat{u} & \sim \Distr{N}\Paran{\mat{0}_D, \mat{V}_u} \\
\mat{e} & \sim \Distr{N}\Paran{\mat{0}_D, \mat{V}_e}
\end{align*}
}where the notation is the same as for the FH model with the following
differences: $\mat{u} = \mat{u}_1$ with $\mat{u}_1$ being the $(D \times 1)$
vector of spatially correlated random effects following a SAR(1):
\empty{
\begin{align*}
u_{1i} & = \rho_1 \sum_{l\neq i}w_{il} u_{1l} + \epsilon_{1i} \\
\epsilon_{1i} & \sim \Distr{N}(0, \sigma_1^2) \text{ i.i.d.}
\end{align*}
}with $i = 1, \dots, D$, where $w_{il}$ are the elements of the row
standardised proximity matrix $\mat{W}$. Let $\mat{W}^0$ denote the proximity
matrix then one possible definition of $\mat{W}^0$ is that the elements are
equal to one if area $i$ and $l$ are neighboured and zero otherwise. This leads
to the following distribution of $\mat{u}_1$:
\empty{
\begin{align*}
\mat{u}_1 & \sim \Distr{N}\Paran{\mat{0}_D, \sigma_{1}^2 \pmat\Omega_1(\rho_1)}
\intertext{where}
\pmat\Omega_1 = \pmat\Omega_1(\rho_1) & = \Paran{(\mat{I}_{D} - \rho_1\mat{W})^\top (\mat{I}_{D} - \rho_1\mat{W})}^{-1}
\end{align*}
}thus $\mat{V}_u = \sigma_{1}^2 \pmat\Omega_1(\rho_1)$. Furthermore
$\mat{u}_1$ and $\mat{e}$ are independent. The unknown model parameters are
$\pmat\beta$ and $\pmat\delta = (\rho_1, \sigma_1^2)$.


## Temporal Fay-Herriot Model

A review of temporal extensions can be found in section
\ref{sec:theory_sae_fh_temporal}. In the following the representation of the
temporal model in \eq{eq:tfh} is reviewed as a linear mixed model of the form:
\empty{
\begin{align*}
\mat{y} & = \mat{X} \pmat\beta + \mat{Z}\mat{u} + \mat{e} \\
\mat{u} & \sim \Distr{N}\Paran{\mat{0}_{D+DT}, \mat{V}_u} \\
\mat{e} & \sim \Distr{N}\Paran{\mat{0}_{DT}, \mat{V}_e}
\end{align*}
}where $\mat{y}$ denotes the $(DT \times 1)$ vector of observed direct 
estimates; $\mat{X}$ the $(DT \times P)$ design matrix; $\pmat\beta$ the $(P 
\times 1)$ vector of regression coefficients; $\mat{Z} = (\mat{Z}_1, \mat{Z}_2)$
where $\mat{Z}_1 = \mat{I}_{D} \otimes (\mat{1}_T)^\top$, $\mat{1}_T$
is a $T \times 1$ vector of ones, and $\mat{Z}_2 = \mat{I}_{DT}$; $\mat{u} =
(\mat{u}_0, \mat{u}_2)$ is the $(D + DT \times 1)$ vector of random effects; and
$\mat{e}$ is the $(DT \times 1)$ vector of sampling errors. Note that
$\mat{u}_0$ denotes the vector of random effects similar to the FH model in that
$\mat{u}_0 \sim \Distr{N}(\mat{0}_D, \sigre\mat{I}_D)$. $\mat{u}_2$ is a $(DT
\times 1)$ vector of autocorrelated random effects following a AR(1):
$$
\re_{2it} = \rho_2 \re_{2i, t-1} + \epsilon_{2it}
$$
with $i = 1, \dots, D$ and $t = 1, \dots, T$, where $\rho_2$ is the auto
correlation coefficient with $|\rho_2| < 1$ and $\epsilon_{2it} \sim
\Distr{N}(0, \sigma_2^2)$. Furthermore $\mat{u}_0$, $\mat{u}_2$ and $\mat{e}$
are pairwise independent. The distribution of $\mat{u}_2$ is given by:
\empty{
\begin{align*}
\mat{u}_2 \sim \Distr{N}\Paran{\mat{0}_{DT}, \sigma_2^2\pmat\Omega_2(\rho_2)} 
\end{align*}
}where $\pmat\Omega_2 = \pmat\Omega_2(\rho_2)$ is a block diagonal matrix in which each block is defined by:
$$
\pmat\Omega_{2i}(\rho_2) = \frac{1}{1-\rho_2^2}
\left(
  \begin{matrix}
    1 & \rho_2 & \cdots & \rho_2^{T-2}& \rho_2^{T-1}\\
    \rho_2 & 1 & & & \rho_2^{T-2} \\
    \vdots & & \ddots & & \vdots \\
    \rho_2^{T-2} &&& 1 & \rho_2 \\
    \rho_2^{T-1} & \rho_2^{T-2} & \cdots & \rho_2 & 1\\
  \end{matrix}
\right)_{T\times T}
$$
with $i = 1, \dots, D$. Thus $\mat{V}_u = \mat{V}_u(\pmat\delta) = 
\Diag{\sigma_\re^2 \mat{I}_{D}, \sigma_2^2\pmat\Omega(\rho_2)}$ is the variance 
covariance matrix of $\mat{u}$; and $\mat{V}_e = \Diag{\{\{\sigma_{eit}^2\}_{t =
1}^T\}_{i = 1}^D}$ is the variance covariance matrix of $\mat{e}$ with known
sampling variances for each time period and area. Hence the unknown model 
parameters are $\pmat\beta$ and $\pmat\delta = (\sigre, \rho_2, \sigma_2^2)$.


## Spatio-Temporal Fay-Herriot Model

A review of this model can be found in Section
\ref{sec:theory_sae_fh_spatio_temporal}. In the following model \eq{eq:stfh} by
@Mar13 is reviewed as a linear mixed model of the from:
\empty{
\begin{align*}
\mat{y} & = \mat{X} \pmat\beta + \mat{Z}\mat{u} + \mat{e} \\
\mat{u} & \sim \Distr{N}\Paran{\mat{0}_{D+DT}, \mat{V}_u} \\
\mat{e} & \sim \Distr{N}\Paran{\mat{0}_{DT}, \mat{V}_e}
\end{align*}
}where the notation is the same as for the temporal model with the following 
differences: here $\mat{u} = (\mat{u}_1, \mat{u}_2)$ where $\mat{u}_1$ denotes 
the spatially correlated random effect also defined for the spatial model and 
$\mat{u}_2$ the autocorrelated random effect as defined for the temporal model.
Thus the variance structure of $\mat{u}$ is given by $\mat{V}_u =
\mat{V}_u(\pmat\delta) = \Diag{\sigma_1^2\pmat\Omega_1(\rho_1),
\sigma_2^2\pmat\Omega_2(\rho_2)}$ and hence the unknown model parameters are
$\pmat\beta$ and $\pmat\delta = (\rho_1, \sigma_1^2, \rho_2, \sigma_2^2)$.


# Robust Predictions under Area Level Models

In the following the concrete approach for the outlier robust predictions under
area level models is layed out. The approach is kept in general notation for
linear mixed models where the spatio and temporal extensions can be framed as
special cases within this class of models. 

## Robust Estimation Equations

In principle I follow the approach by @Sin09 which is to start with the
dirivatives with respect to $\pmat\beta$ and $\pmat\delta$ of the marginal
log-likelihood of $\mat{y}$:
\empty{
\begin{align*}
\mat{X}^\top\mat{V}^{-1}\left(\mat{y}-\mat{X}\pmat\beta\right) &= 0 \\
\intertext{and}
\left(\mat{y} - \mat{X}\pmat\beta\right)^\top\mat{V}^{-1}          %(y-Xb)'V^-1
\frac{\partial\mat{V}}{\partial\delta_l}                      % dV/dx
\mat{V}^{-1}\left(\mat{y} - \mat{X}\pmat\beta\right) -             %V^-1 (y-Xb)
\tr\left(\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_l}\right) &= 0
\end{align*}
}with $l = 1, \dots, Q$ where $Q$ denotes the total number of variance 
parameters in $\pmat\delta$. @Sin09 proposed to *robustify* these equations by
replacing them with:
\empty{
\begin{align}
\label{eq:rfhreeb}
\mat{X}^\top\mat{V}^{-1} \mat{U}^{\frac{1}{2}} \psi(\mat{r}) & = 0
\intertext{and}
\label{eq:rfhreed}
\psi(\mat{r})^\top\mat{U}^{\frac{1}{2}}\mat{V}^{-1}
\frac{\partial\mat{V}}{\partial\delta_l}
\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_l}\right) & = 0
\end{align}
}where $\mat{K} = \Exp{E}(\psi_b^2(z)) \mat{I}_n$ is a diagonal matrix of the
same order as $\mat{V}$ with $z$ following a standard normal distribution; and 
$\mat{r} = \mat{r}(\pmat\beta) = \mat{U}^{-\half} (\mat{y} - \mat{X}\pmat\beta)$
denotes the vector of the standardised residuals and $\mat{U} = 
\mat{U}(\pmat\delta)$ is the matrix containing the diagonal elements of 
$\mat{V}$. Furthermore $\psi_b(x) = x \min\Paran{1, \frac{b}{|x|}}$ is the 
influence function proposed by @Hub64 for a given tuning constant $b$ where a 
common choice for $b$ is 1.345 - see @Sin09. These robust estimation equations
are being utilised also for the area level models under study. A difference will
be to find solutions to these equations which is outlined later in this Section.

For the random effect, $\mat{u}$, @Sin09 propose to use the estimation equations
proposed by @Fel86 given in \eq{eq:rmmere}. This estimation equation is based on
the derivative of the log-likelihood function of the joint probability
distribution of $\mat{u}$ and $\mat{y}$ with respect to $\mat{u}$:
$$
\mat{Z}^\top \mat{V}_e^{-1} \Paran{\mat{y}-\mat{X}\pmat\beta - \mat{Z} \mat{\re}} - \mat{V}_\re^{-1} \mat{\re} = 0.
$$
The idea of the robust version is now to restrict the influence of $\mat{u}$ and
$\mat{e}$ in the estimation equation using the same influence function as
before. However, instead of using the robust estimation equation by @Fel86:
\empty{
\begin{align}
\mat{Z}^\top \mat{V}_e^{-\half} \psi \Paran{\mat{V}_e^{-\half} \Paran{\mat{y}-\mat{X}\pmat\beta - \mat{Z} \mat{\re}}}
- \mat{V}_\re^{-\half} \psi\Paran{\mat{V}_\re^{-\half}\mat{\re}} & = 0 \nonumber \\
\intertext{I propose the following form:}
\mat{Z}^\top \mat{V}_e^{-1} \mat{U}_e^{\half} \psi \Paran{\mat{U}_e^{-\half} \Paran{\mat{y}-\mat{X}\pmat\beta - \mat{Z} \mat{\re}}}
- \mat{V}_\re^{-1} \mat{U}_u^{\half} \psi\Paran{\mat{U}_u^{-\half} \mat{\re}} & = 0 \label{eq:rfheere}
\end{align}
}where $\mat{U}_e$ and $\mat{U}_u$ denote diagonal matrices with the 
diagonal elements of $\mat{V}_e$ and $\mat{V}_u$, respectively. This
modification is very similar to the idea by @Sin09 in that only the diagonal
elements are used to standardize the residuals. In fact this modification is
not necessary for the robust BHF model or a robust FH model because for these
models $\mat{V}_u$ is a diagonal matrix. This is not the case, however, in the
setting of correlated random effects - e. g. in the case of a SAR(1) or AR(1)
model - which motivates this extensions.

Let $\tilde{\pmat\beta}^\psi$ and $\tilde{\mat{u}}^\psi$ define the solutions for known variance parameters, $\pmat\delta$, to the robust estimation equations \eq{eq:rfhreeb} and \eq{eq:rfheere}, respectively. Then the area level RBLUP can be defined as:
\empty{
\begin{align}
\label{eq:area_rblup}
\tilde{\theta}_i^{RBLUP} 
  = \mat{x}_i^\top\tilde{\pmat\beta}^\psi + \mat{z}_i^\top \tilde{\mat{u}}^\psi
\end{align}
}with $i = 1, \dots, n$ where $n$ can be the number of domains, $D$, or for the 
temporal and spatio\hyp{}temporal model $DT$. Here $\mat{x}_i$ denotes the $(P
\times 1)$ vector of auxiliary information for the $i$th observation and
$\mat{z}_i$ similarly the column vector containing the $i$th row in $\mat{Z}$
where the form of $\mat{Z}$ depends on the specific model. Here 
\eq{eq:area_rblup} acts as a placeholder for the area level spatial RBLUP 
(SRBLUP), the temporal RBLUP (TRBLUP), and the spatio\hyp{}temporal RBLUP 
(STRBLUP). The RBLUP depends on the unknown variance parameters, $\pmat\delta$,
which need to be estimated. If we replace $\pmat\delta$ with the robust
parameter estimates $\hat{\pmat\delta}^\psi$ we denote $\hat{\pmat\beta}^\psi$
and $\hat{\mat{u}}^\psi$ as robust solutions and hence the REBLUP can be derived
as:
\empty{
\begin{align}
\label{eq:area_reblup}
\hat{\theta}_i^{REBLUP} 
  = \mat{x}_i^\top\hat{\pmat\beta}^\psi + \mat{z}_i^\top \hat{\mat{u}}^\psi.
\end{align}
}Here the area level spatial REBLUP (SREBLUP), the temporal REBLUP (TREBLUP),
and the spatio\hyp{}temporal REBLUP (STREBLUP) are special cases of
\eq{eq:area_reblup}.


## Pseudolinear Representation

The solutions to the estimation equations \eq{eq:rfhreeb} and \eq{eq:rfheere} 
are derived from the pseudolinear form of the RBLUP which follows a similar form
as for the RBLUP under the unit level model by @Cha14 which was reviewed in
Section \ref{sec:theory_sae_robust_mspe}. Hence following this idea the area
level RBLUP \eq{eq:area_rblup} can be rewritten into:
\empty{
\begin{align*}
\tilde{\theta}_i^{RBLUP} 
  & = \mat{x}_i^\top\tilde{\pmat\beta}^\psi + \mat{z}_i^\top \tilde{\mat{u}}^\psi \\
  & = \Paran{\mat{x}_i^\top\mat{A} + \mat{z}_i^\top \mat{B} \Paran{\mat{I}_n - \mat{X} \mat{A}}} \mat{y} \\
  & = \tilde{\mat{w}}_i^\top \mat{y}
\end{align*}
}where $\tilde{\mat{w}}_i$ denotes the vector of weights. 

In the following I want to motivate the specific form of $\mat{A}$ and 
$\mat{B}$. Note that $\mat{A}\mat{y} = \tilde{\pmat\beta}^\psi$ and that the
specific form of $\mat{A}$ can be derived starting from the estimation equation
in
\eq{eq:rfhreeb}:
\empty{
\begin{align*}
\mat{X}^\top\mat{V}^{-1} \mat{U}^{\half} 
  \psi\Paran{\mat{U}^{-\half} (\mat{y} - \mat{X}\pmat\beta)} & = 0 \\
\mat{X}^\top\mat{V}^{-1} \mat{U}^{\half} \mat{W}_1 \mat{U}^{-\half} 
  (\mat{y} - \mat{X}\pmat\beta) & = 0 \\
\underbrace{\mat{X}^\top\mat{V}^{-1} \mat{W}_1}_{\mat{W}_1^*} (\mat{y} - \mat{X}\pmat\beta) & = 0 \\
\mat{W}_1^* \mat{y} & = \mat{W}_1^* \mat{X}\pmat\beta \\
\underbrace{\Paran{\mat{W}_1^* \mat{X}}^{-1} \mat{W}_1^*}_{\mat{A}} 
  \mat{y} & = \pmat\beta
\end{align*}
}where $\mat{W}_1 = \mat{W}_1(\pmat\beta) = \Diag{\{w_{1i}\}_{i = 1}^n}$ is a
diagonal matrix with the elements defined by:
$$
w_{1i} = 
  \psi\Paran{U_i^{-\half} (y_i - \mat{x}_i^\top\pmat\beta)} 
  \Paran{U_i^{-\half} (y_i - \mat{x}_i^\top\pmat\beta)}^{-1}
$$
where $U_i^{-\half}$ is the $i$th diagonal element of $\mat{U}^{-\half}$. Note 
that the extension is possible because $\mat{U}$ is a diagonal matrix.
Furthermore the form can be simplified because $\mat{U}^\half$, $\mat{W}_1$, and
$\mat{U}^{-\half}$ are also diagonals. Hence
\empty{
\begin{align*}
\mat{A} = \mat{A}(\pmat\beta) = \Paran{\mat{X}^\top\mat{V}^{-1} \mat{W}_1
  \mat{X}}^{-1} \mat{X}^\top\mat{V}^{-1} \mat{W}_1
\end{align*}
}which is similar to the form derived by @Cha14 for the robust BHF model. And more correctly we can write now $\mat{A}(\tilde{\pmat\beta}^\psi)\mat{y} = \tilde{\pmat\beta}^\psi$.

To derive $\mat{B}$ note that:
\empty{
\begin{align*}
\tilde{\mat{u}}^\psi 
  & = \mat{B}\Paran{\mat{I} - \mat{X}\mat{A}} \mat{y} \\
  & = \mat{B}\Paran{\mat{y} - \mat{X}\beta}
\end{align*}
}and that the approach taken is similar as for $\mat{A}$. However the form of 
$\mat{B}$ is different from the approach by @Cha14 because of the different 
estimation equation for the random effects \eq{eq:rfheere}. This different form 
simplifies the form of the two weighting matrices - $\mat{W}_1$ and $\mat{W}_2$
in the following equations - as they are also diagonal matrices. Thus starting
from \eq{eq:rfheere} the specific form of $\mat{B}$ can be derived as:
\empty{
\begin{align*}
\mat{Z}^\top \mat{V}_e^{-1} \mat{U}_e^{\half} \psi \Paran{\mat{U}_e^{-\half} 
  \Paran{\mat{y}-\mat{X}\beta - \mat{Z} \mat{\re}}} 
  - \mat{V}_\re^{-1} \mat{U}_\re^\half \psi\Paran{\mat{U}_\re^{-\half}\mat{\re}} & = 0 \\
%
\mat{Z}^\top \mat{V}_e^{-1} \mat{U}_e^\half \mat{W}_2 \mat{U}_e^{-\half}
  \Paran{\mat{y}-\mat{X}\beta - \mat{Z} \mat{\re}} 
  - \mat{V}_\re^{-1} \mat{U}_\re^\half \mat{W}_3 \mat{U}_\re^{-\half} \mat{\re} & = 0 \\
%
\underbrace{\mat{Z}^\top \mat{V}_e^{-1} \mat{W}_2}_{\mat{W}^*_2}
  \Paran{\mat{y}-\mat{X}\beta - \mat{Z} \mat{\re}} 
  - \underbrace{\mat{V}_\re^{-1}  \mat{W}_3 }_{\mat{W}_3^*} \mat{\re} & = 0
%
\end{align*}
}where I continue with $\mat{W}_2^*$ and $\mat{W}_3^*$ to simplify the notation.
As before $\mat{U}_e^\half$, $\mat{U}_e^{-\half}$, $\mat{U}_\re^\half$, and
$\mat{U}_\re^{-\half}$ cancel out because they are diagonal matrices as well as
$\mat{W}_2$ and $\mat{W}_3$. Continuing:
\empty{
\begin{align*}
\mat{W}_2^* \Paran{\mat{y}-\mat{X}\beta - \mat{Z} \mat{\re}} & = 
  \mat{W}_3^*\mat{\re} \\
%
\mat{W}_2^* \Paran{\mat{y}-\mat{X}\beta} & = 
  \Paran{\mat{W}_2^*\mat{Z} + \mat{W}_3^*} \mat{\re} \\
%
\underbrace{\Paran{\mat{W}_2^*\mat{Z} + \mat{W}_3^*}^{-1} \mat{W}_2^*}_{\mat{B}} 
  \Paran{\mat{y}-\mat{X}\beta} & = \mat{\re}
\end{align*}
}and thus 
\empty{
\begin{align*}
\mat{B}(\mat{u}, \pmat\beta) = \mat{B} = &
  \Paran{
    \mat{Z}^\top \mat{V}_e^{-1} \mat{W}_2 \mat{Z} + \mat{V}_\re^{-1} \mat{W}_3}^{-1} 
    \mat{Z}^\top \mat{V}_e^{-1} \mat{W}_2 
\end{align*}
}where $\mat{W}_2 = \mat{W}_2(\pmat\beta)$ is a $(n \times n)$ diagonal matrix
with elements:
\empty{
\begin{align*}
w_{2i} = 
  \psi\Paran{U_{ei}^{-\half} (y_i - \mat{x}_i^\top\pmat\beta)} 
  \Paran{U_{ei}^{-\half} (y_i - \mat{x}_i^\top\pmat\beta)}^{-1}
\end{align*}
}where $U_{ei}^{-\half}$ denote the diagonal elements of $\mat{U}_e^{-\half}$; 
and $\mat{W}_3 = \mat{W}_3(\mat{u})$ is a $(m \times m)$ diagonal matrix with
elements:
\empty{
\begin{align*}
w_{3j} = 
  \psi\Paran{U_{uj}^{-\half} u_j} 
  \Paran{U_{uj}^{-\half} u_j}^{-1}
\end{align*}
}where $U_{uj}^{-\half}$ denote the diagonal elements of $\mat{U}_\re^{-\half}$ 
and $m$ the number of elements in $\mat{u}$. Now we can state more precisely: 
$$\mat{B}(\tilde{\mat{u}}^\psi, \tilde{\pmat\beta}^\psi)\Paran{\mat{y} -
\mat{X}\tilde{\pmat\beta}^\psi} = \tilde{\mat{u}}^\psi.$$
This approach can be adapted for the REBLUP in \eq{eq:area_reblup} when we
replace the model parameters by their estimators $\hat{\pmat\beta}^\psi$ and
$\hat{\pmat\delta}^\psi$ and the prediction for $\mat{u}$ with
$\hat{\mat{u}}^\psi$. Then the area level REBLUP is given by:
\empty{
\begin{align*}
\hat{\theta}_i^{REBLUP} 
  & = \hat{\mat{w}}_i^\top \mat{y}.
\end{align*}
}where $\hat{\mat{w}}_i$ denotes the vector of weights depending on the
estimated model parameters. This representation leads to two important results.
First the derivation of an iterative solution for the estimation equations
\eq{eq:rfhreeb} and \eq{eq:rfheere} which are presented in the following
section; and second an analytical MSPE estimator similar to the proposition by
@Cha11 which is presented in section (?).


## Solutions to the Robust Estimation Equations

For the solutions of the robust estimation equations I begin with the solution
for the regression coefficients. Recall that:
\empty{
\begin{align*}
\pmat\beta = \mat{A}(\pmat\beta)\mat{y}
\end{align*}
}and that $\hat{\pmat\beta}^\psi = \mat{A}\Paran{\hat{\pmat\beta}^\psi}\mat{y}$.
This representation indicates that we have a fixed point function for 
$\pmat\beta$ which, in this special case, leads to an iterative re-weighted
least squares (IRWLS) algorithm to solve \eq{eq:rfhreeb} for $\pmat\beta$:
\empty{
\begin{align*}
\pmat\beta^{(m + 1)} 
  & = \mat{A}\Paran{\pmat\beta^{(m)}}\mat{y} \\
  & = \Paran{\mat{X}^\top\mat{V}^{-1} \mat{W}_1(\pmat\beta^{(m)}) \mat{X}}^{-1} \mat{X}^\top\mat{V}^{-1} \mat{W}_1(\pmat\beta^{(m)}) \mat{y}
\end{align*}
}for adequate starting values $\pmat\beta^{(0)}$ and known variance parameters
$\pmat\delta$. This proposition is very similar to the IRWLS algorithm suggested
by @Schoch12 however it depends on a differnt choice for the robust estimation
equation. Details on IRWLS algorithms for robust M-estimation can also be found 
in @Mar06[pp. 104-105]. A natural choice as a starting value for the weighting 
matrix is to set the diagonal elements to one. This will lead to the non robust 
generalised least squares estimator in the first iteration. This solution is 
acceptabel since - as @Mar06[pp. 104-105] note - for a continuous choice of
$\psi$ the algorithm is non sensetive to the starting values with respect to 
convergence. Bad starting values can however increase the number of iterations. 
Note also that this iterative algorithm has the desirable property that it 
reduces to the GLS estimator if we set the tuning constant of $\psi_b$ to 
infinity because of the special form of $\mat{W}_1$.

Similarly a fixed point function for $\mat{u}$ can be defined by:
\empty{
\begin{align*}
\mat{u} & = \mat{B}(\mat{u})\Paran{\mat{y} - \mat{X}\beta}
\end{align*}
}where we can define an algorithm for known regression coefficients,
$\pmat\beta$, and variance parameters, $\pmat\delta$:
\empty{
\begin{align*}
\mat{u}^{(m + 1)} 
  = & \mat{B}(\mat{u}^{(m)})\Paran{\mat{y} - \mat{X}\beta} \\
  = & \Paran{\mat{Z}^\top \mat{V}_e^{-1} \mat{W}_2 \mat{Z} + \mat{V}_\re^{-1} \mat{W}_3(\mat{u}^{(m)})}^{-1} \\
  & \times \mat{Z}^\top \mat{V}_e^{-1} \mat{W}_2 \Paran{\mat{y} - \mat{X}\beta}
\end{align*}
}with suitable starting values $\mat{u}^{(0)}$. The starting values can be 
chosen similar to the IRWLS algorithm in that we set the diagonal elements in
$\mat{W}_3$ to one. Similar to the IRWLS algorithm before, if the tuning 
constant of the influence function is chosen to be infinity the algorithm has 
the desiarable property that it reduces to the form of the non\hyp{}robust 
estimation equation of \eq{eq:rfheere} because of the special form of 
$\mat{W}_2$ and $\mat{W}_3$, i.e. they reduce to identity matrices. And - as it 
was reviewed in Section \ref{sec:robustee} - the solution to the non\hyp{}robust
equation \eq{eq:rfheere} is equivalent the the BLUP for $\mat{u}$ given by
\eq{eq:blupre}.

An algorithm to solve for $\pmat\delta$ was derived by (?) for the case of the
robust BHF model. I follow hear the same general procedure to derive fixed point
equations. In contrast to the solution of $\pmat\beta$ and $\mat{u}$ this
algorithm depends on the specific form of the variance matrix of the random
effects and hence needs to be derieved for each model individually. However
consider the general algorithm:
\empty{
\begin{align*}
\pmat\delta^{(m + 1)} = \mat{C}(\pmat\delta^{(m)})^{-1} \mat{D}(\pmat\delta^{(m)})
\end{align*}
}where $\mat{C}$ and $\mat{D}$ denote matrices depending on $\pmat\delta$ and we
assume that the inverse of $\mat{C}$ exists. The specific form of $\mat{C}$ and
$\mat{D}$ is the the subject matter of the following sections.

The algorithm is now:

1. Choose initial values $\pmat\beta^{(0)}$ and $\pmat\delta^{(0)}$ and set $m = 0$.
2. Compute $\pmat\beta^{(m + 1)}$ using equation (?) with given parameters
$\pmat\delta^{(m)}$ until convergence is reached.
3. With $\pmat\beta^{(m + 1)}$ compute $\pmat\delta^{(m + 1)}$ using equation (?).
4. Set $m = m + 1$
3. Repeat steps 2. to 4. until the set of parameters jointly reaches
convergence. Declare these solutions to be the robust parameter estimates
$\hat{\pmat\beta}^\psi$ and $\hat{\pmat\delta}^\psi$.
4. With the solutions $\hat{\pmat\beta}^\psi$ and $\hat{\pmat\delta}^\psi$ compute $\mat{u}^{(m +
1)}$ using equation (?) until convergence is reached.


### Solutions for the Robust FH Model

Starting from equation \ref{eq:rfhreed} where $\pmat\delta = (\sigre)$ we can
rewrite the equation such that:
\empty{
\begin{align}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigre}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigre} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1} (\mat{Z}\mat{V}_u\mat{Z}^\top)\right) \label{eq:reeefhsigma}
\end{align}
}where under the FH model $\mat{Z} = \mat{I}_D$, $\mat{V}_u = \sigre\mat{I}_D$, and $\partial\mat{V} / \partial\sigre = \mat{I}_D$ and hence \eq{eq:reeefhsigma} simplifies to:
\empty{
\begin{align*}
0 = \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
  - \tr\left(\mat{K}\mat{V}^{-1} \sigma_\re^{-2} \sigre\right).
\end{align*}
}Solving this equation for $\sigre$ we can write:
\empty{
\begin{align*}
\sigre = 
  \tr\left(\mat{K}\mat{V}^{-1} \sigma_\re^{-2} \right)^{-1} 
  \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
\end{align*}
}which is the fixed point function and leads to the iterative equation:
\empty{
\begin{align*}
\delta^{(m + 1)} = 
  \Paran{\underbrace{\tr\left(\mat{K}\mat{V}^{-1} \sigma_\re^{-2} \right)}_{C(\delta^{(m)})}}^{-1} 
  \underbrace{\psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})}_{D(\delta^{(m)})}
\end{align*}
}where $C(\delta)$ and $D(\delta)$ are scalars under the FH model with $\delta =
\sigre$.


### Solutions for the Spatial Robust FH Model

In principle the derivation for the spatio temporal extensions follows the same 
procedure as before; however adpated for the more complex variance structure of
the specific models. Under the spatial FH model we have $\pmat\delta = (\rho_1, 
\sigma_1^2)$ and split up the derivation into an algorithm for $\delta_\rho =
(\rho_1)$ and $\delta_\sigma = (\sigma_1^2)$. Starting, again, from \eq{eq:rfhreed}
\empty{
\begin{align}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\sigma}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\sigma} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1} (\mat{Z}\mat{V}_u\mat{Z}^\top)\right) \label{eq:reesrfhsigma}
\end{align}
}where we can recall that $\mat{Z} = \mat{I}_D$, $\mat{V}_u =
\sigma_1^2\pmat\Omega_1(\rho_1)$, and thus $\partial\mat{V} /
\partial\delta_\sigma = \pmat\Omega_1(\rho_1)$. Hence we can write
\eq{eq:reesrfhsigma} as:
\empty{
\begin{align*}
0 = 
\psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1} \pmat\Omega_1 \mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) 
- \tr\left(\mat{K}\mat{V}^{-1} \pmat\Omega_1 \sigma_1^{-2} \pmat\Omega_1^{-1} \sigma_1^2 \pmat\Omega_1 \right)
\end{align*}
}and solving for $\sigma_1^2$ leads to:
\empty{
\begin{align*}
\sigma_1^2 = \tr\left(\mat{K}\mat{V}^{-1} \sigma_1^{-2} \pmat\Omega_1 \right)^{-1} \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1} \pmat\Omega_1 \mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) 
\end{align*}
}which is the fixed point function for $\sigma_1^2$ and leads to the following iterative equation:
\empty{
\begin{align*}
\delta_\sigma^{(m + 1)} = 
  \Paran{\underbrace{\tr\left(\mat{K}\mat{V}^{-1} \sigma_1^{-2} \pmat\Omega_1 \right)}_{C(\delta_\sigma^{(m)})}}^{-1}
  \underbrace{\psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1} \pmat\Omega_1 \mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})}_{D(\delta_\sigma^{(m)})}
\end{align*}
}

Similarly we can derive an algorithm for $\rho_1$ where we can start from the definition of $\pmat\Omega_1$:
\empty{
\begin{align*}
\pmat\Omega_1(\rho_1) 
  & = \Paran{\Paran{\mat{I}_D - \rho_1\mat{W}}^\top\Paran{\mat{I}_D - \rho_1\mat{W}}}^{-1} \\
  & = \pmat\Omega_1 \pmat\Omega_1 \Paran{\mat{I}_D - \rho_1\mat{W}}^\top\Paran{\mat{I}_D - \rho_1\mat{W}} \\
  & = \rho_1 \underbrace{\pmat\Omega_1 \pmat\Omega_1 \Paran{\mat{I}_D - \rho_1\mat{W}}^\top\Paran{\rho_1^{-1} \mat{I}_D - \mat{W}}}_{\pmat\Omega_1^*}
\end{align*}
}and hence $\mat{V}_u = \sigma_1^2\rho_1\pmat\Omega_1^*$. Now we can start again
from \eq{eq:rfhreed} 
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho} \Paran{\rho_1\sigma_1^2\pmat\Omega_1^*}^{-1} \Paran{\rho_1\sigma_1^2\pmat\Omega_1^*} \right)
\end{align*}
}where:
\empty{
\begin{align*}
\frac{\partial\mathbf{V}}{\partial\rho_1} 
  & = - \sigma_1^2 \pmat\Omega_1 \frac{\partial\pmat\Omega_1^{-1}}{\partial\rho_1} \pmat\Omega_1 \\
\intertext{and}
\frac{\partial\pmat\Omega_1^{-1}}{\partial\rho_1} 
  & = -\mathbf{W} - \mathbf{W}^\top + 2\rho_1\mathbf{W}^\top\mathbf{W}
\end{align*}
}which we can solve for $\rho_1$:
\empty{
\begin{align*}
\rho_1 = 
  \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho} \rho_1^{-1} \right)^{-1}
  \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) 
\end{align*}
}from which the following iterative equation can be derived:
\empty{
\begin{align*}
\rho_1^{(m + 1)} = 
  \Paran{\underbrace{\tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho} \rho_1^{-1} \right)}_{C(\rho_1^{(m)})}}^{-1}
  \underbrace{\psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_\rho}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})}_{D(\rho_1^{(m)})}
\end{align*}
}

### Solutions for the Temporal Robust FH Model

For the solutions for the temporal FH model recall that $\pmat\delta = (\sigre, \rho_2, \sigma_2^2)$ and that $\mat{V}_u = \Diag{\sigre\mat{I}, \sigma_2^2\pmat\Omega_2(\rho_2)}$. $\delta_\sigma = (\sigre, \sigma_2^2)$ then we can start from \eq{eq:rfhreed} with:
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1} (\mat{Z}\mat{V}_u\mat{Z}^\top)\right)
\end{align*}
}
\empty{
\begin{align*}
\mat{V}_u
  =& \left(\begin{matrix}
    \sigre\mat{I}_D & \mat{0}_{D\times DT}\\
    \mat{0}_{DT\times D} &  \sigma_2^2\pmat\Omega_2
    \end{matrix}\right) \\
  =& \sigre
      \left(\begin{matrix}
      \mat{I}_D & \mat{0}_{D\times DT} \\
      \mat{0}_{DT\times D} &  \mat{0}_{DT\times DT}
      \end{matrix}\right)
    +
    \sigma_2^2\left(\begin{matrix}
    \mat{0}_{D\times D} & \mat{0}_{D\times DT} \\
    \mat{0}_{DT\times D} & \pmat\Omega_2
    \end{matrix}\right) \\
  =& \left(\begin{matrix}\bar{\mat{I}} & \bar{\pmat\Omega}_2\end{matrix}\right)
    \left(\begin{matrix}
    \sigre \\
    \sigma_2^2
    \end{matrix}\right)
\end{align*}
}and hence we can write:
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\underbrace{\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1}}_{\mat{C}^*(\delta_{\sigma l})}
  \left(\begin{matrix}\mat{Z}\bar{\mat{I}}\mat{Z}^\top & \mat{Z}\bar{\pmat\Omega}_2\mat{Z}^\top\end{matrix}\right)
    \left(\begin{matrix}
    \sigre \\
    \sigma_2^2
    \end{matrix}\right)\right)
\end{align*}
}which we can now solve for $\pmat\delta_\sigma$:
\empty{
\begin{align*}
\pmat\delta_\sigma = \mat{C}(\pmat\delta_\sigma)^{-1}\mat{D}(\pmat\delta_\sigma)
\end{align*}
}where
\empty{
\begin{align*}
\mat{C}(\pmat\delta_\sigma)
  = \left(\begin{matrix}
      \tr\left(\mat{C}^*(\sigre) \mat{Z}\bar{\mat{I}}\mat{Z}^\top \right) &
      \tr\left(\mat{C}^*(\sigre) \mat{Z}\bar{\Omega}_2\mat{Z}^\top \right) \\
      \tr\left(\mat{C}^*(\sigma_2^2) \mat{Z}\bar{\mat{I}}\mat{Z}^\top \right) &
      \tr\left(\mat{C}^*(\sigma_2^2) \mat{Z}\bar{\Omega}_2\mat{Z}^\top \right)
    \end{matrix}\right)
\end{align*}
}and
\empty{
\begin{align*}
\mat{D}(\pmat\delta_\sigma) =
  \left(\begin{matrix}
    \psi(\mat{r})^\top\mat{U}^{\frac{1}{2}}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigre}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \\
    \psi(\mat{r})^\top\mat{U}^{\frac{1}{2}}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigma_2^2}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
  \end{matrix}\right)
\end{align*}
}where we have to devine the derivatives. $\partial\mat{V} / \partial\sigre =
\mat{Z}_1\mat{I}_D\mat{Z}_1^\top$ and
$\partial\mat{V} / \partial\sigma_2^2 = \pmat\Omega_2$.

Now missing is still a solution for $\delta_\rho = (\rho_2)$. Starting from \eq{eq:rfhreed} we can write:
\empty{
\begin{align*}
0 = \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
  - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho}} \delta_{\rho}^{-1} \delta_{\rho}\right)
\end{align*}
}and solve for $\delta_{\rho}$:
\empty{
\begin{align*}
\delta_{\rho} = 
  \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho}} \delta_{\rho}^{-1} \right)
  \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
\end{align*}
}where we have
\empty{
\begin{align*}
\frac{\partial\mathbf{V}}{\partial\rho_2} = & \sigma_2^2 \Diag{\left\{\frac{\partial\pmat\Omega_{2i}}{\partial\rho_2}\right\}_{i = 1}^D} \\
\intertext{with}
\frac{\partial\pmat\Omega_{2i}}{\partial\rho_2} = & \frac{1}{1-\rho_2^2}
\left(
\begin{matrix}
0 & 1 & \cdots & \cdots & (T-1)\rho_2^{T-2}\\
1 & 0 & & & (T-2)\rho_2^{T-3} \\
\vdots & & \ddots & & \vdots \\
(T-2)\rho_2^{T-3} &&& 0 & 1 \\
(T-1)\rho_2^{T-2} & \cdots & \cdots & 1 & 0\\
\end{matrix}
\right) \\ & + \frac{2\rho_2\pmat\Omega_{2d}}{1-\rho_2^2}
\end{align*}
}


### Solutions for the Spatio\hyp{}Temporal Model

Starting from equation \eq{eq:rfhreed} where $\pmat\delta = (\rho_1, \sigma_1^2,
\rho_2, \sigma_2^2)$ and we split again the problem into finding solutions for
$\pmat\delta_\rho = (\rho_1, \rho_2)$ and $\pmat\delta_\sigma = (\sigma_1^2,
\sigma_2^2)$. In both cases we can start from:
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_l}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \\
  & - \tr\left(\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{l}} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1} (\mat{Z}\mat{V}_u\mat{Z}^\top) \right)
\end{align*}
}where $\partial\delta_{l}$ denotes an element in either $\pmat\delta_\rho$ or $\pmat\delta_\sigma$. For the solutions of $\pmat\delta_\sigma$ we begin similar to the temporal extension in that we can write:
\empty{
\begin{align*}
\mat{V}_u
  =& \left(\begin{matrix}
    \sigma_1^2 \pmat\Omega_1 & \mat{0}_{D\times DT}\\
    \mat{0}_{DT\times D} &  \sigma_2^2\pmat\Omega_2
    \end{matrix}\right) \\
  =& \sigma_1^2
      \left(\begin{matrix}
      \pmat\Omega_1 & \mat{0}_{D\times DT} \\
      \mat{0}_{DT\times D} &  \mat{0}_{DT\times DT}
      \end{matrix}\right)
    +
    \sigma_2^2\left(\begin{matrix}
    \mat{0}_{D\times D} & \mat{0}_{D\times DT} \\
    \mat{0}_{DT\times D} & \pmat\Omega_2
    \end{matrix}\right) \\
  =& \left(\begin{matrix}\bar{\pmat\Omega}_1 & \bar{\pmat\Omega}_2\end{matrix}\right)
    \left(\begin{matrix}
    \sigma_1^2 \\
    \sigma_2^2
    \end{matrix}\right)
\end{align*}
}and hence
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\underbrace{\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\sigma l}} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1}}_{\mat{C}^*(\delta_{\sigma l})}
  \left(\begin{matrix}\mat{Z}\bar{\pmat\Omega}_1\mat{Z}^\top & \mat{Z}\bar{\pmat\Omega}_2\mat{Z}^\top\end{matrix}\right)
    \left(\begin{matrix}
    \sigma_1^2 \\
    \sigma_2^2
    \end{matrix}\right)\right)
\end{align*}
}which we can solve now for $\pmat\delta_\sigma$:
\empty{
\begin{align*}
\pmat\delta_\sigma = \mat{C}(\pmat\delta_\sigma)^{-1}\mat{D}(\pmat\delta_\sigma)
\end{align*}
}where
\empty{
\begin{align*}
\mat{C}(\pmat\delta_\sigma)
  = \left(\begin{matrix}
      \tr\left(\mat{C}^*(\sigma_1^2) \mat{Z}\bar{\pmat\Omega}_1\mat{Z}^\top \right) &
      \tr\left(\mat{C}^*(\sigma_1^2) \mat{Z}\bar{\Omega}_2\mat{Z}^\top \right) \\
      \tr\left(\mat{C}^*(\sigma_2^2) \mat{Z}\bar{\pmat\Omega}_1\mat{Z}^\top \right) &
      \tr\left(\mat{C}^*(\sigma_2^2) \mat{Z}\bar{\Omega}_2\mat{Z}^\top \right)
    \end{matrix}\right)
\end{align*}
}and
\empty{
\begin{align*}
\mat{D}(\pmat\delta_\sigma) =
  \left(\begin{matrix}
    \psi(\mat{r})^\top\mat{U}^{\frac{1}{2}}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigma_1^2}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \\
    \psi(\mat{r})^\top\mat{U}^{\frac{1}{2}}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\sigma_2^2}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r})
  \end{matrix}\right)
\end{align*}
}where $\partial\mat{V} / \partial\sigma_2^2$ is defined as for the temporal model and $\partial\mat{V} / \partial\sigma_1^2 = \mat{Z}_1 \pmat\Omega_1 \mat{Z}_1^\top$. And for $\pmat\delta_\rho$:
\empty{
\begin{align*}
\mat{V}_u
  =& \left(\begin{matrix}
    \sigma_1^2 \rho_1 \pmat\Omega_1^* & \mat{0}_{D\times DT}\\
    \mat{0}_{DT\times D} &  \sigma_2^2 \rho_2 \pmat\Omega_2^*
    \end{matrix}\right) \\
  =& \rho_1
      \left(\begin{matrix}
      \sigma_1^2 \pmat\Omega_1^* & \mat{0}_{D\times DT} \\
      \mat{0}_{DT\times D}       & \mat{0}_{DT\times DT}
      \end{matrix}\right)
    +
    \rho_2 \left(\begin{matrix}
    \mat{0}_{D\times D} & \mat{0}_{D\times DT} \\
    \mat{0}_{DT\times D} & \sigma_2^2 \pmat\Omega_2^*
    \end{matrix}\right) \\
  =& \left(\begin{matrix}\bar{\pmat\Omega}_1^* & \bar{\pmat\Omega}_2^* \end{matrix}\right)
    \left(\begin{matrix}
    \rho_1 \\
    \rho_2
    \end{matrix}\right)
\end{align*}
}where $\pmat\Omega_1^*$ is defined as for the spatial FH model in section (?) and
\empty{
\begin{align*}
\pmat\Omega_2(\rho_2) & = \rho_2 \underbrace{\Diag{\left\{\pmat\Omega_{2i}^*\right\}_{i = 1}^D}}_{\pmat\Omega_2^*}
\intertext{with}
\pmat\Omega_{2i}^* & = \frac{1}{\rho_2-\rho_2^3}
\left(
  \begin{matrix}
    1 & \rho_2 & \cdots & \rho_2^{T-2}& \rho_2^{T-1}\\
    \rho_2 & 1 & & & \rho_2^{T-2} \\
    \vdots & & \ddots & & \vdots \\
    \rho_2^{T-2} &&& 1 & \rho_2 \\
    \rho_2^{T-1} & \rho_2^{T-2} & \cdots & \rho_2 & 1\\
  \end{matrix}
\right)_{T\times T}.
\end{align*}
}With this rewriting we can now write:
\empty{
\begin{align*}
0 = & \psi(\mat{r})^\top \mat{U}^{\half}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho l}}\mat{V}^{-1}\mat{U}^{\frac{1}{2}} \psi(\mat{r}) \nonumber\\
  & - \tr\left(\underbrace{\mat{K}\mat{V}^{-1}\frac{\partial\mat{V}}{\partial\delta_{\rho l}} (\mat{Z}\mat{V}_u\mat{Z}^\top)^{-1}}_{\mat{C}^*(\delta_{\rho l})}
  \left(\begin{matrix}\mat{Z}\bar{\pmat\Omega}_1^*\mat{Z}^\top & \mat{Z}\bar{\pmat\Omega}_2^*\mat{Z}^\top\end{matrix}\right)
    \left(\begin{matrix}
    \rho_1 \\
    \rho_2
    \end{matrix}\right)\right)
\end{align*}
}where $\partial\mat{V} / \partial\rho2$ is the same as for the temporal model and
\empty{
\begin{align*}
\frac{\partial\mat{V}}{\partial\rho_1} 
  =& -\sigma_1^2\mat{Z}_1\pmat\Omega_1\frac{\partial\pmat\Omega_1^{-1}}{\partial\rho_1}\pmat\Omega_1\mat{Z}^\top_1 \\
\intertext{with}
\frac{\partial\pmat\Omega_1^{-1}}{\partial\rho_1}
  =& -\mathbf{W} - \mathbf{W}^\top + 2\rho_1\mathbf{W}^\top\mathbf{W}
\end{align*}
}

